version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oerinspanish"
s3_prefix = "oerinspanish"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
