version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oerinspanish"
s3_prefix = "oerinspanish"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9aai0x6lvksf"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
